services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      - DB_NAME=pern_project
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_HOST=172.17.0.1
      - DB_PORT=5432
    ports:
      - '5000:5000'
    # depends_on:
    # - postgres
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dev
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'

    mem_limit: 512m
    cpus: 1.0

#   postgres:
#     image: postgres
#     ports:
#       - '5432:5432'
#     environment:
#       - POSTGRES_DB=pern_project
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=root
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - dev
#     mem_limit: 512m
#     cpus: 1.0

# volumes:
#   pgdata:

networks:
  dev:
