user  root;
worker_processes  1;

events {
}

http {
    server {
        listen       80;
        server_name  localhost;  # Corrected server_name

        location / {
            proxy_pass http://frontend:3000;  # Assuming frontend is a service in your Docker network
        }

        location /api {  # Example of a different location block for backend
            proxy_pass http://backend:5000;  # Assuming backend is a service in your Docker network
        }

        # Uncomment and configure error pages if needed
        # error_page  404 /404.html;
        # error_page  500 502 503 504 /50x.html;
        # location = /50x.html {
        #     root html;
        # }
    }

    # Additional server blocks can be added here
}